### ISSUE TITLE
error Couldn't find any versions for "xmldom" that matches "^0.8.3"

### ISSUE THREAD

**Issue by jizusun** [jquad-group/backstage-jquad#4]
I tried to set up CI, but came across the issue

https://github.com/jizusun/backstage-jquad/actions/runs/3279332667/jobs/5398748592

```sh
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Lockfile has incorrect entry for "xmldom@^0.8.3". Ignoring it.
error Couldn't find any versions for "xmldom" that matches "^0.8.3"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by rannox** [comment]
Hi! 

i tried to update the packages, that had security issues using `resolutions`: https://github.com/jquad-group/backstage-jquad/blob/main/package.json#L43. Maybe the `resolutions` broke the build. 

Although I think we should remove the `resolutions`, because those libraries are used in Backstage, and they should be updated there?

**Comment by jizusun** [comment]
Oh I see, the `resolution` is a feature of `yarn v1` https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
And I guess maybe the `"xmldom@^0.8.3` is wrong?

**Comment by rannox** [comment]
Sorry for the late answer, yeah it was wrong, the resolutions are now fixed. I am closing this issue, feel free to open it again, if needed :)
